name: Deploy Minecraft Server and Commit Changes

on:
  push:
    branches:
      - main

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y wget screen

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Verify Java Installation
        run: java -version

      - name: Verify Server File
        run: ls -l server.jar

      - name: Start Minecraft Server
        run: |
          # Start the Minecraft server in a detached screen session
          screen -dmS mc_server /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.4-7/x64/bin/java -Xmx10G -XX:+UseG1GC -jar server.jar nogui
          echo "Minecraft server started in detached screen session."

          # Wait for 5 hours to ensure the server has time to run
          echo "Waiting for 5 hours..."
          sleep 18000

          # Capture the output of the Minecraft server
          echo "Capturing server output..."
          screen -list
          screen -r mc_server -X hardcopy ~/server_output.log
          echo "Server output captured."

          # Display the server output log
          echo "Displaying server output log:"
          cat ~/server_output.log

      - name: Upload Server Logs
        uses: actions/upload-artifact@v3
        with:
          name: server-logs
          path: ~/server_output.log

  commit-changes:
    runs-on: ubuntu-latest
    needs: start-server
    if: success() || failure()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global credential.helper store
          echo "https://:${{ secrets.GIT_AUTH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Wait before starting commit
        run: sleep 120 # Wait for 2 minutes

      - name: Continuous Commit
        run: |
          while true; do
            git diff --exit-code || (git add . && git commit -m "Update server deployment workflow" && git push)
            sleep 10
          done
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
